### Creating Commutator and Generator Table of Size n x n

#### Marcus K

\[Explanation of what is going on here\]

In [2]:
import numpy as np

class CommutatorGeneratorTables:
    def __init__(self, A=None, B=None, size=3):
        # Initialize matrices A and B for commutator table and size for generator table
        self.A = A if A is not None else np.random.rand(3, 3)
        self.B = B if B is not None else np.random.rand(3, 3)
        self.size = size
        self.commutator_table = None
        self.generator_table = None

    def zeta(self, g_i, g_j):
        # Define the commutator function zeta(g_i, g_j)
        commutator = g_i * g_j - g_j * g_i  # [g_i, g_j]
        anticommutator = g_i * g_j + g_j * g_i  # {g_i, g_j}
        
        if commutator == 0:
            return 1  # [g_i, g_j] = 0
        elif anticommutator == 0:
            return -1  # {g_i, g_j} = 0
        else:
            return 0  # Default value if not meeting either condition

    def create_commutator_table(self):
        # Create the commutator table
        self.commutator_table = np.zeros((self.A.shape[0], self.B.shape[1]), dtype=int)

        for i in range(self.A.shape[0]):
            for j in range(self.B.shape[1]):
                try:
                    self.commutator_table[i, j] = self.zeta(self.A[i, j], self.B[i, j])
                except ValueError:
                    self.commutator_table[i, j] = 0  # Set a default value for undefined cases

        return self.commutator_table

    def generator_zeta(self, i, j):
        # Define the function for the generator table based on Kronecker delta
        return 1 - 2 * (i == j)  # Returns 1 - 2*delta_{ij}

    def create_generator_table(self):
        # Create the generator table
        self.generator_table = np.zeros((self.size, self.size), dtype=int)

        for i in range(self.size):
            for j in range(self.size):
                self.generator_table[i, j] = self.generator_zeta(i, j)

        return self.generator_table

# Example usage
tables = CommutatorGeneratorTables()
commutator_table = tables.create_commutator_table()
generator_table = tables.create_generator_table()


print("Commutator Table:")
print(commutator_table)

print("\nGenerator Table:")
print(generator_table)






Commutator Table:
[[1 1 1]
 [1 1 1]
 [1 1 1]]

Generator Table:
[[-1  1  1]
 [ 1 -1  1]
 [ 1  1 -1]]
