In [3]:
!pip install scipy

   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   - -------------------------------------- 2.1/44.5 MB 11.8 MB/s eta 0:00:04
   ---- ----------------------------------- 4.7/44.5 MB 12.4 MB/s eta 0:00:04
   ------ --------------------------------- 7.6/44.5 MB 13.1 MB/s eta 0:00:03
   --------- ------------------------------ 11.0/44.5 MB 13.8 MB/s eta 0:00:03
   ------------ --------------------------- 13.9/44.5 MB 13.6 MB/s eta 0:00:03
   --------------- ------------------------ 17.6/44.5 MB 14.2 MB/s eta 0:00:02
   ------------------ --------------------- 20.7/44.5 MB 14.5 MB/s eta 0:00:02
   --------------------- ------------------ 24.1/44.5 MB 14.5 MB/s eta 0:00:02
   ------------------------ --------------- 27.3/44.5 MB 14.8 MB/s eta 0:00:02
   ------------------------- -------------- 28.0/44.5 MB 13.7 MB/s eta 0:00:02
   -------------------------- ------------- 29.9/44.5 MB 13.2 MB/s eta 0:00:02
   ---------------------------- ----------- 32.2/44.5 MB 13.0 MB

In [1]:
# Import type hints for better code readability
from typing import List

class Solution:
    def multiply(self, mat1: List[List[int]], mat2: List[List[int]]) -> List[List[int]]:
        # Helper function to create a sparse matrix representation
        def create_sparse_matrix(matrix: List[List[int]]) -> List[List[tuple]]:
            # Initialize a list to store the sparse representation
            sparse_matrix = [[] for _ in range(len(matrix))]
            # Iterate through the matrix to record non-zero values along with their column indexes
            for row_index, row in enumerate(matrix):
                for col_index, value in enumerate(row):
                    if value:
                        # Append a tuple containing the column index and the value if non-zero
                        sparse_matrix[row_index].append((col_index, value))
            return sparse_matrix
      
        # Create the sparse matrix representations for both input matrices
        sparse_mat1 = create_sparse_matrix(mat1)
        sparse_mat2 = create_sparse_matrix(mat2)
      
        # Get the dimensions for the resulting matrix
        m, n = len(mat1), len(mat2[0])
      
        # Initialize the resulting matrix with zeros
        result_matrix = [[0] * n for _ in range(m)]
      
        # Iterate through each row of mat1
        for i in range(m):
            # Iterate through the sparse representation of the row from mat1
            for col_index_mat1, value_mat1 in sparse_mat1[i]:
                # For non-zero elements in mat1's row, iterate through the corresponding row in mat2
                for col_index_mat2, value_mat2 in sparse_mat2[col_index_mat1]:
                    # Multiply and add to the resulting matrix
                    result_matrix[i][col_index_mat2] += value_mat1 * value_mat2
                  
        # Return the resulting matrix after multiplication
        return result_matrix

In [5]:
import numpy as np
from scipy.sparse import csr_matrix

# Define three sparse matrices in CSR format
A = csr_matrix([[1, 0, 0], [0, 0, 2], [0, 3, 0]])
B = csr_matrix([[0, 4, 0], [5, 0, 0], [0, 0, 6]])
C = csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 0]])

# Perform the multiplication of three sparse matrices: A * B * C
D = A.dot(B).dot(C)

# Convert the result to a dense matrix for display
result = D.toarray()
print("Result of sparse matrix multiplication (A * B * C):\n", result)



Result of sparse matrix multiplication (A * B * C):
 [[ 0 12  0]
 [48  0  0]
 [15  0 30]]


In [6]:
import numpy as np
from scipy.sparse import csr_matrix

def sparse_multiply_three(A, B, C):
    """
    Perform sparse matrix multiplication for three matrices: A, B, and C.

    Parameters:
        A (csr_matrix): The first sparse matrix.
        B (csr_matrix): The second sparse matrix.
        C (csr_matrix): The third sparse matrix.

    Returns:
        csr_matrix: The result of A * B * C as a sparse matrix.
    """
    # Ensure the matrices are in CSR format for efficient multiplication
    A = csr_matrix(A)
    B = csr_matrix(B)
    C = csr_matrix(C)

    # Perform the multiplication: (A * B) * C
    result = A.dot(B).dot(C)

    # Return the resulting sparse matrix
    return result

# Example usage
A = csr_matrix([[1, 0, 0], [0, 0, 2], [0, 3, 0]])
B = csr_matrix([[0, 4, 0], [5, 0, 0], [0, 0, 6]])
C = csr_matrix([[1, 0, 2], [0, 3, 0], [4, 0, 0]])

# Call the function
result = sparse_multiply_three(A, B, C)

# Display the result as a dense matrix
print("Result of A * B * C:\n", result.toarray())


Result of A * B * C:
 [[ 0 12  0]
 [48  0  0]
 [15  0 30]]


In [7]:
import numpy as np

def twirl_operator(W, M):
    """
    Perform the twirling operation on the matrix M using the twirling set W.

    Parameters:
        W (list of numpy arrays): The twirling set, a list of matrices.
        M (numpy array): The matrix (noise operator) to be twirled.

    Returns:
        numpy array: The resulting twirled matrix.
    """
    # Get the size of the twirling set
    n = len(W)
    
    # Initialize the result matrix with zeros of the same shape as M
    twirled_matrix = np.zeros_like(M, dtype=complex)
    
    # Iterate over each matrix w in the twirling set W
    for w in W:
        twirled_matrix += w @ M @ w.conj().T

    # Divide by the size of the twirling set
    twirled_matrix /= n

    return twirled_matrix

# Example usage
# Define the twirling set (list of matrices)
W = [
    np.array([[1, 0], [0, 1]]),  # Identity matrix
    np.array([[0, 1], [1, 0]]),  # Pauli-X matrix
    np.array([[0, -1j], [1j, 0]]),  # Pauli-Y matrix
    np.array([[1, 0], [0, -1]])  # Pauli-Z matrix
]

# Define the noise operator M
M = np.array([[0.5, 0.5], [0.5, 0.5]])

# Call the function
result = twirl_operator(W, M)

# Print the result
print("Twirled matrix:\n", result)


Twirled matrix:
 [[0.5+0.j 0. +0.j]
 [0. +0.j 0.5+0.j]]
